### PR TITLE
fix(nextjs): add honeybadger in external packages

### LINKED ISSUE #1351: Loading the config cause `Critical dependency: the request of a dependency is an expression`
## What are the steps to reproduce this issue?
1. Setup a Next.js project (our project is using 14.1.3)
2. Add Honeybadger following https://docs.honeybadger.io/lib/javascript/integration/nextjs/
3. Run next dev
4. Load a page

## What happens?
Each time a new page is loaded the logs below are generated

## What were you expecting to happen?
The dependency is loaded without the logging noise

## Any logs, error output, etc?
```
 ⚠ ./node_modules/@honeybadger-io/js/dist/server/honeybadger.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/@honeybadger-io/js/dist/server/honeybadger.js
[omitted]
```

## Any other comments?
Honeybadger still seems to be working, but the logging noise isn't great.

I believe this was introduce with PR #1268 specifically this [line](https://github.com/honeybadger-io/honeybadger-js/pull/1268/files#diff-a238576a4dd76ae3f749332d8c8383b877bd4ea24267197419505936bc080bd0R83).

## What versions are you using?
**Operating System:** Intel MacOS 13.6.6 (22G630)
**Package Name:** @honeybadger-io/nextjs
**Package Version:** 5.8.14
**Browser Version:** n/a

### PR DESCRIPTION
**Pull request by subzero10**
## Status
**READY**

## Description
Fixes #1351.
Adds `@honeybadger-io/js` to external packages, since it uses Node.js `require` to import configuration files dynamically.

### CODE REVIEW

File: packages/nextjs/src/index.ts [hunk 1]
```diff
@@ -165,6 +165,50 @@ function getWebpackPluginOptions(honeybadgerNextJsConfig: HoneybadgerNextJsConfi
...
+
+  if (config.experimental?.serverComponentsExternalPackages && Array.isArray(config.experimental?.serverComponentsExternalPackages)) {
+    log('debug', 'adding @honeybadger-io/js to experimental.serverComponentsExternalPackages')
+    config.experimental.serverComponentsExternalPackages.push('@honeybadger-io/js')
+    return
+  }
+
+  const nextJsVersion = getNextJsVersionInstalled();
+  if (nextJsVersion) {
+    if (+nextJsVersion[0] >= 14 && +nextJsVersion[1] >= 3) {
```
Comment (subzero10) [inline packages/nextjs/src/index.ts:198]: This is the option available in the [documentation](https://nextjs.org/docs/app/api-reference/next-config-js/serverExternalPackages) today, but it's not available with the current latest stable release (14.2.3), so I took a guess here and assumed that the next minor version should have it.

**Review by joshuap — APPROVED** [review]
Looks good to me.
