### PR TITLE
fix(core): log correct endpoint used

### LINKED ISSUE #1451: Wrong domain used in console log
A customer using the EU stack noticed that the following console message was pointing to the wrong domain:

```
Error report sent ⚡ https://app.honeybadger.io/notice/${uuid}
```

### PR DESCRIPTION
**Pull request by subzero10**
## Status
**READY**

## Description
Note: The log message used to point to APP Honeybadger, but since `endpoint` is configurable, we shouldn't hardcode the log to the APP domain. Therefore, I changed to simply log the url that was used to submit the notice.

Fixes #1451

### CODE REVIEW

File: packages/core/src/client.ts [hunk 1]
```diff
@@ -487,7 +489,7 @@ export abstract class Client {
         runAfterNotifyHandlers(merge(notice, {
           id: uuid
         }), this.__afterNotifyHandlers)
-        this.logger.info(`Error report sent ⚡ https://app.honeybadger.io/notice/${uuid}`)
+        this.logger.info(`Error report sent to ⚡ ${endpointUrl}`)
```
Comment (stympy) [inline packages/core/src/client.ts:492]: I don't think this right... we don't want to be displaying the same URL that is used to submit notices to the API. Instead we want to display the corresponding _app_ URL with the `notice/${uuid}` path so that the user can click that link and be redirected to the error detail page in the UI.

File: packages/js/src/server/check-ins-manager/client.ts [hunk 2]
```diff
@@ -22,7 +21,7 @@ export class CheckInsClient {
     const response = await this.transport.send({
       method: 'GET',
       headers: this.getHeaders(),
-      endpoint: `${this.BASE_URL}/v2/project_keys/${projectApiKey}`,
+      endpoint: Util.endpoint(this.config.appEndpoint, `v2/project_keys/${projectApiKey}`),
```
Comment (subzero10) [inline packages/js/src/server/check-ins-manager/client.ts:24]: `Util.endpoint` is a helper method that provides safer URL generation.
If `this.config.appEndpoint` is _https://app.honeybadger.io/_ or  _https://app.honeybadger.io_, the generated URL will be the same.
