### PR TITLE
#722 Respect toJSON in `breadrumb.metadata`

### LINKED ISSUE #722: `toJSON` not respected in honeybadger sanitize
## What are the steps to reproduce this issue?
1. Add breadcrumb with metadata containing an object with a `toJSON`
2. Send a honeybadger notice

## What happens?
The metadata field in the breadcrumb just says `[object Object]`

## What were you expecting to happen?
It would use `toJSON` to expand it and then sanitize

## Any other comments?
The reason we want to do this is we do our own sanitization and eventual stringify of the breadcrumb metadata field but we don't want to do this eagerly since it wastes time and only want to do it at the point of reporting the error.

## What versions are you using?
**Operating System:** Linux
**Package Version:** 3.2.1
**Browser Version:** Firefox 98

### PR DESCRIPTION
**Pull request by subzero10**
## Status
**READY**

## Description
Fixes #722.
Respects `toJSON()` in `util.sanitize()`.

## Todos
- [x] Tests
- [x] getJson() method that respects toJSON of objects  
- [x] Changelog Entry (unreleased)

### CODE REVIEW

File: src/core/util.ts [hunk 1]
```diff
@@ -105,7 +105,7 @@ export function runAfterNotifyHandlers(notice: Notice | null, handlers: AfterNot
 }
 
 // Returns a new object with properties from other object.
-export function newObject<T>(obj: T): T | Record<string, unknown> {
+export function shallowClone<T>(obj: T): T | Record<string, unknown> {
```
Comment (subzero10) [inline src/core/util.ts:108]: I think `shallowClone` makes better sense.

File: src/core/util.ts [hunk 2]
```diff
@@ -116,6 +116,23 @@ export function newObject<T>(obj: T): T | Record<string, unknown> {
...
+  if (typeof obj.toJSON === 'function') {
+    return obj.toJSON()
+  }
+
+  const result = {}
+  for (const k in obj) {
+    result[k] = typeof obj[k] === 'object' ? getJson(obj[k]) : obj[k]
+  }
+
+  return result
```
Comment (subzero10) [inline src/core/util.ts:133]: This could be simplified to `JSON.parse(JSON.stringify(obj))`, though I think the current solution is better for performance.

Comment (subzero10) [reply src/core/util.ts]: I ended up using `JSON.parse(JSON.stringify(obj))` because integration tests where failing and I couldn't figure out why.

**Comment by subzero10** [comment]
Here's a working example:
Screenshot 2022-04-01 at 8 58 09 PM
Screenshot 2022-04-01 at 8 58 14 PM

File: src/core/util.ts [hunk 3]
```diff
@@ -134,8 +134,14 @@ export function sanitize(obj, maxDepth = 8) {
   }
 
   function canSerialize(obj) {
-    // Functions are TMI and Symbols can't convert to strings.
-    if (/function|symbol/.test(typeof (obj))) {
+    // Functions are TMI
+    if (/function/.test(typeof (obj))) {
+      // Let special toJSON method pass as it's used by JSON.stringify (#722)
+      return obj.name === 'toJSON';
```
Comment (subzero10) [inline src/core/util.ts:140]: @joshuap Here's the solution we discussed about.

**Review by joshuap — APPROVED** [review]
Looks great, thanks!

**Comment by subzero10** [comment]
@shipjs prepare
